import type { Metadata } from "next";
import { Figtree} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "FrondEndMentor",
  description: "Generated by create next app",
};

export const figtree = Figtree({
  variable: "--font-Figtree",
  subsets: ["latin"],
  weight: ["500" , "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

